# Generated by Django 4.2.13 on 2024-05-31 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_alter_space_image_alter_tag_post'),
        ('posts', '0003_alter_post_content_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='space',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
    ]
