# Generated by Django 4.2.13 on 2024-06-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_alter_space_image_alter_tag_post'),
        ('posts', '0004_post_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
    ]
