# Generated by Django 4.2.13 on 2024-06-18 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_commentlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactiontype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'post', 'reaction_type')},
        ),
    ]
