# Generated by Django 4.2.13 on 2024-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_reactiontype_icon_alter_reaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactiontype',
            name='icon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
