# Generated by Django 4.2.13 on 2024-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
