# Generated by Django 4.2.13 on 2024-08-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postimages_savedposts_unique_user_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
