# Generated by Django 4.2.13 on 2024-05-21 19:26

from django.db import migrations, models
import django.utils.timezone
import spaces.validators


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_space_updated_at_space_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(validators=[spaces.validators.validate_description_len]),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=30, validators=[spaces.validators.validate_name_len]),
        ),
    ]
