# Generated by Django 4.2.13 on 2024-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_content_alter_post_name'),
        ('spaces', '0004_space_image_alter_space_description_alter_space_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='posts.post'),
        ),
    ]
