# Generated by Django 4.2.13 on 2024-05-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_space'),
        ('spaces', '0005_alter_space_image_alter_tag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(to='posts.post'),
        ),
    ]
