# Generated by Django 4.2.13 on 2024-07-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_userspacefollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
