# Generated by Django 4.2.13 on 2024-07-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_space_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
