# Generated by Django 4.2.13 on 2024-08-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visibility',
            field=models.CharField(choices=[('M', 'Me'), ('F', 'Followers'), ('P', 'Public')], default='P', max_length=1),
        ),
    ]
