# Generated by Django 4.2.13 on 2024-08-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visibility',
            field=models.CharField(choices=[('M', 'Само аз'), ('F', 'Само последователи'), ('P', 'Публично')], default='P', max_length=1),
        ),
    ]
