# Generated by Django 4.2.13 on 2024-08-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Следване')], default='follow', max_length=20),
            preserve_default=False,
        ),
    ]
