# Generated by Django 4.2.13 on 2024-09-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Следване'), ('reply', 'Отговор'), ('post_created', 'Публикация създадена'), ('post_deleted', 'Публикация изтрита'), ('space_created', 'Тема създадена'), ('space_deleted', 'Тема изтрита')], max_length=20),
        ),
    ]
